import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';

// Take control of all clients as soon as the service worker is activated
clientsClaim();

// Clean up outdated caches
cleanupOutdatedCaches();

// Precache all the assets generated by your bundler
precacheAndRoute(self.__WB_MANIFEST);

// Cache the Google Fonts stylesheets with a stale-while-revalidate strategy
registerRoute(
    ({ url }) => url.origin === 'https://fonts.googleapis.com',
    new StaleWhileRevalidate({
        cacheName: 'google-fonts-stylesheets',
    }),
);

// Cache the underlying font files with a cache-first strategy for 1 year
registerRoute(
    ({ url }) => url.origin === 'https://fonts.gstatic.com',
    new CacheFirst({
        cacheName: 'google-fonts-webfonts',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 30,
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
            }),
        ],
    }),
);

// Cache images with a cache-first strategy
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'images',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 60,
                maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
            }),
        ],
    }),
);

// Skip waiting and claim clients immediately
self.skipWaiting();

// Handle offline fallback
const FALLBACK_HTML_URL = '/offline.html';
const OFFLINE_VERSION = 1;

// Install event - cache offline fallback
self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(`offline-${OFFLINE_VERSION}`).then((cache) => {
            return cache.add(FALLBACK_HTML_URL);
        }),
    );
});

// Fetch event - serve offline fallback when needed
self.addEventListener('fetch', (event) => {
    if (event.request.mode === 'navigate') {
        event.respondWith(
            fetch(event.request).catch(() => {
                return caches.open(`offline-${OFFLINE_VERSION}`).then((cache) => {
                    return cache.match(FALLBACK_HTML_URL);
                });
            }),
        );
    }
});

// Activate event - cleanup old caches
self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys().then((cacheNames) => {
            return Promise.all(
                cacheNames
                    .filter(
                        (cacheName) => cacheName.startsWith('offline-') && cacheName !== `offline-${OFFLINE_VERSION}`,
                    )
                    .map((cacheName) => caches.delete(cacheName)),
            );
        }),
    );
});
